/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package imageeditor;

import javax.swing.ImageIcon;

/**
 *
 * @author Leonardo
 */
public class ImageEditor extends javax.swing.JFrame {
    ProcesamientoImagen ObjProcesamiento=new ProcesamientoImagen();
    private boolean rot=false;
    private Histogram his=new Histogram();
    
    public ImageEditor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem4 = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLabel1 = new javax.swing.JLabel();
        Close = new javax.swing.JButton();
        Umbral = new javax.swing.JSlider();
        jLabel2 = new javax.swing.JLabel();
        UniqueColor = new javax.swing.JTextField();
        UmbralNumber = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        Contraste = new javax.swing.JSlider();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ContrasteNumber = new javax.swing.JSpinner();
        Brillo = new javax.swing.JSlider();
        BrilloNumber = new javax.swing.JSpinner();
        Rotacion = new javax.swing.JSlider();
        RotacionNumber = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        RotacionCheck = new javax.swing.JCheckBox();
        UmbralButtom = new javax.swing.JButton();
        BrilloButtom = new javax.swing.JButton();
        ContrastButtom = new javax.swing.JButton();
        RotacionButtom = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        DPI = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Width = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Height = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        BitsPixel = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        Histogram = new javax.swing.JButton();
        convy = new javax.swing.JSpinner();
        jLabel13 = new javax.swing.JLabel();
        convx = new javax.swing.JSpinner();
        jLabel14 = new javax.swing.JLabel();
        pivoty = new javax.swing.JSpinner();
        pivotx = new javax.swing.JSpinner();
        jLabel15 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        UploadImage = new javax.swing.JMenuItem();
        SaveAs = new javax.swing.JMenuItem();
        RemoveFilters = new javax.swing.JMenuItem();
        Filter = new javax.swing.JMenu();
        GrayScale = new javax.swing.JMenuItem();
        BlackAndWhite = new javax.swing.JMenuItem();
        Negative = new javax.swing.JMenuItem();
        Rotate = new javax.swing.JMenu();
        Right = new javax.swing.JMenuItem();
        Left = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        ZoomIn = new javax.swing.JMenuItem();
        ZoomOut = new javax.swing.JMenuItem();
        Sobel = new javax.swing.JMenuItem();
        Roberts = new javax.swing.JMenuItem();
        Prewitt = new javax.swing.JMenuItem();
        laplaceGauss = new javax.swing.JMenuItem();
        promedio = new javax.swing.JMenuItem();
        mediana = new javax.swing.JMenuItem();
        filtroCustom = new javax.swing.JMenuItem();

        jMenuItem4.setText("jMenuItem4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Editor de Imagenes");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        setSize(new java.awt.Dimension(0, 0));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(jLabel1);

        Close.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Close.setText("Cerrar");
        Close.setFocusable(false);
        Close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseActionPerformed(evt);
            }
        });

        Umbral.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        Umbral.setMajorTickSpacing(255);
        Umbral.setMaximum(255);
        Umbral.setPaintLabels(true);
        Umbral.setPaintTicks(true);
        Umbral.setValue(150);
        Umbral.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Umbral.setEnabled(false);
        Umbral.setFocusable(false);
        Umbral.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                UmbralStateChanged(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel2.setText("Colores Unicos");

        UniqueColor.setEditable(false);
        UniqueColor.setBackground(new java.awt.Color(255, 255, 255));
        UniqueColor.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        UniqueColor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        UniqueColor.setFocusable(false);

        UmbralNumber.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        UmbralNumber.setModel(new javax.swing.SpinnerNumberModel(150, 0, 255, 1));
        UmbralNumber.setToolTipText("");
        UmbralNumber.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        UmbralNumber.setEnabled(false);
        UmbralNumber.setFocusable(false);
        UmbralNumber.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                UmbralNumberStateChanged(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel3.setText("Umbral");

        jButton1.setText("jButton1");

        jButton2.setText("jButton2");

        Contraste.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        Contraste.setMajorTickSpacing(100);
        Contraste.setMinimum(-100);
        Contraste.setMinorTickSpacing(-100);
        Contraste.setPaintLabels(true);
        Contraste.setPaintTicks(true);
        Contraste.setValue(0);
        Contraste.setEnabled(false);
        Contraste.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                ContrasteStateChanged(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel4.setText("Brillo");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel5.setText("Contraste");

        ContrasteNumber.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        ContrasteNumber.setModel(new javax.swing.SpinnerNumberModel(0, -100, 100, 1));
        ContrasteNumber.setToolTipText("");
        ContrasteNumber.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ContrasteNumber.setEnabled(false);
        ContrasteNumber.setFocusable(false);
        ContrasteNumber.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                ContrasteNumberStateChanged(evt);
            }
        });

        Brillo.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        Brillo.setMajorTickSpacing(255);
        Brillo.setMaximum(255);
        Brillo.setMinimum(-255);
        Brillo.setMinorTickSpacing(-255);
        Brillo.setPaintLabels(true);
        Brillo.setPaintTicks(true);
        Brillo.setValue(0);
        Brillo.setEnabled(false);
        Brillo.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                BrilloStateChanged(evt);
            }
        });

        BrilloNumber.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        BrilloNumber.setModel(new javax.swing.SpinnerNumberModel(0, -255, 255, 1));
        BrilloNumber.setToolTipText("");
        BrilloNumber.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BrilloNumber.setEnabled(false);
        BrilloNumber.setFocusable(false);
        BrilloNumber.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                BrilloNumberStateChanged(evt);
            }
        });

        Rotacion.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        Rotacion.setMajorTickSpacing(360);
        Rotacion.setMaximum(360);
        Rotacion.setPaintLabels(true);
        Rotacion.setPaintTicks(true);
        Rotacion.setValue(0);
        Rotacion.setEnabled(false);
        Rotacion.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                RotacionStateChanged(evt);
            }
        });

        RotacionNumber.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        RotacionNumber.setModel(new javax.swing.SpinnerNumberModel(0, 0, 360, 1));
        RotacionNumber.setToolTipText("");
        RotacionNumber.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        RotacionNumber.setEnabled(false);
        RotacionNumber.setFocusable(false);
        RotacionNumber.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                RotacionNumberStateChanged(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel6.setText("Rotacion Libre");

        RotacionCheck.setEnabled(false);
        RotacionCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RotacionCheckActionPerformed(evt);
            }
        });

        UmbralButtom.setText("Aplicar");
        UmbralButtom.setEnabled(false);
        UmbralButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UmbralButtomActionPerformed(evt);
            }
        });

        BrilloButtom.setText("Aplicar");
        BrilloButtom.setEnabled(false);
        BrilloButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BrilloButtomActionPerformed(evt);
            }
        });

        ContrastButtom.setText("Aplicar");
        ContrastButtom.setEnabled(false);
        ContrastButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContrastButtomActionPerformed(evt);
            }
        });

        RotacionButtom.setText("Aplicar");
        RotacionButtom.setEnabled(false);
        RotacionButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RotacionButtomActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel7.setText("DPI");

        DPI.setEditable(false);
        DPI.setBackground(new java.awt.Color(255, 255, 255));
        DPI.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        DPI.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        DPI.setFocusable(false);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel8.setText("Dimensiones");

        Width.setEditable(false);
        Width.setBackground(new java.awt.Color(255, 255, 255));
        Width.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Width.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Width.setFocusable(false);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel9.setText("Ancho");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel10.setText("Alto");

        Height.setEditable(false);
        Height.setBackground(new java.awt.Color(255, 255, 255));
        Height.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Height.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Height.setFocusable(false);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel11.setText("Bits por Pixel");

        BitsPixel.setEditable(false);
        BitsPixel.setBackground(new java.awt.Color(255, 255, 255));
        BitsPixel.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        BitsPixel.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        BitsPixel.setFocusable(false);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel12.setText("Colores");

        Histogram.setText("Histograma");
        Histogram.setEnabled(false);
        Histogram.setFocusPainted(false);
        Histogram.setFocusable(false);
        Histogram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HistogramActionPerformed(evt);
            }
        });

        convy.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        convy.setModel(new javax.swing.SpinnerNumberModel(0, 0, 360, 1));
        convy.setToolTipText("");
        convy.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        convy.setEnabled(false);
        convy.setFocusable(false);
        convy.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                convyStateChanged(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel13.setText("Convolucion");

        convx.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        convx.setModel(new javax.swing.SpinnerNumberModel(0, 0, 360, 1));
        convx.setToolTipText("");
        convx.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        convx.setEnabled(false);
        convx.setFocusable(false);
        convx.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                convxStateChanged(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel14.setText("Dimensiones");

        pivoty.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        pivoty.setModel(new javax.swing.SpinnerNumberModel(0, 0, 360, 1));
        pivoty.setToolTipText("");
        pivoty.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pivoty.setEnabled(false);
        pivoty.setFocusable(false);
        pivoty.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                pivotyStateChanged(evt);
            }
        });

        pivotx.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        pivotx.setModel(new javax.swing.SpinnerNumberModel(0, 0, 360, 1));
        pivotx.setToolTipText("");
        pivotx.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pivotx.setEnabled(false);
        pivotx.setFocusable(false);
        pivotx.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                pivotxStateChanged(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel15.setText("Pivote");

        jButton3.setText("Aplicar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jMenu1.setText("Archivo");
        jMenu1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        UploadImage.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        UploadImage.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        UploadImage.setText("Cargar Imagen");
        UploadImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UploadImageActionPerformed(evt);
            }
        });
        jMenu1.add(UploadImage);

        SaveAs.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        SaveAs.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        SaveAs.setText("Guardar Imagen como...");
        SaveAs.setEnabled(false);
        SaveAs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveAsActionPerformed(evt);
            }
        });
        jMenu1.add(SaveAs);

        RemoveFilters.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.CTRL_MASK));
        RemoveFilters.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        RemoveFilters.setText("Deshacer Filtros");
        RemoveFilters.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveFiltersActionPerformed(evt);
            }
        });
        jMenu1.add(RemoveFilters);

        Filter.setText("Filtros");
        Filter.setEnabled(false);
        Filter.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        GrayScale.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        GrayScale.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        GrayScale.setText("Escala de Grises");
        GrayScale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GrayScaleActionPerformed(evt);
            }
        });
        Filter.add(GrayScale);
        GrayScale.getAccessibleContext().setAccessibleDescription("");

        BlackAndWhite.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        BlackAndWhite.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        BlackAndWhite.setText("Blanco y Negro");
        BlackAndWhite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BlackAndWhiteActionPerformed(evt);
            }
        });
        Filter.add(BlackAndWhite);

        Negative.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        Negative.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Negative.setText("Negativo");
        Negative.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NegativeActionPerformed(evt);
            }
        });
        Filter.add(Negative);

        jMenu1.add(Filter);

        Rotate.setText("Rotar 90 grados");
        Rotate.setEnabled(false);
        Rotate.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        Right.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        Right.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Right.setText("Derecha");
        Right.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RightActionPerformed(evt);
            }
        });
        Rotate.add(Right);

        Left.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        Left.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Left.setText("Izquierda");
        Left.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LeftActionPerformed(evt);
            }
        });
        Rotate.add(Left);

        jMenu1.add(Rotate);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Tarea2");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        ZoomIn.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ADD, 0));
        ZoomIn.setText("Zoom In x2");
        ZoomIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZoomInActionPerformed(evt);
            }
        });
        jMenu2.add(ZoomIn);

        ZoomOut.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_SUBTRACT, 0));
        ZoomOut.setText("Zoom Out x2");
        ZoomOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZoomOutActionPerformed(evt);
            }
        });
        jMenu2.add(ZoomOut);

        Sobel.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        Sobel.setText("Sobel");
        Sobel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SobelActionPerformed(evt);
            }
        });
        jMenu2.add(Sobel);

        Roberts.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        Roberts.setText("Roberts");
        Roberts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RobertsActionPerformed(evt);
            }
        });
        jMenu2.add(Roberts);

        Prewitt.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        Prewitt.setText("Prewitt");
        Prewitt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrewittActionPerformed(evt);
            }
        });
        jMenu2.add(Prewitt);

        laplaceGauss.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        laplaceGauss.setText("Laplaciano del Gaussiano");
        laplaceGauss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laplaceGaussActionPerformed(evt);
            }
        });
        jMenu2.add(laplaceGauss);

        promedio.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        promedio.setText("Filtro promedio");
        promedio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                promedioActionPerformed(evt);
            }
        });
        jMenu2.add(promedio);

        mediana.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        mediana.setText("Filtro mediana");
        mediana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medianaActionPerformed(evt);
            }
        });
        jMenu2.add(mediana);

        filtroCustom.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        filtroCustom.setText("Filtro Custom");
        jMenu2.add(filtroCustom);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 626, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Umbral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(UmbralNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(UmbralButtom))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Contraste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ContrasteNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ContrastButtom))
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Brillo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BrilloNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BrilloButtom))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(RotacionCheck))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Rotacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(RotacionNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(RotacionButtom))
                            .addComponent(jLabel13)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(99, 99, 99))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(UniqueColor, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                                    .addComponent(BitsPixel))
                                .addGap(40, 40, 40)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel9)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(Width, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jLabel10)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(Height, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(DPI)))
                                            .addComponent(jLabel7))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel14)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(convx, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(convy, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(jLabel15)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(pivotx, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(pivoty, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton3)))
                                .addGap(94, 94, 94)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Histogram, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Close, javax.swing.GroupLayout.Alignment.TRAILING))))))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Umbral, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(UmbralNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(UmbralButtom)))
                        .addGap(25, 25, 25)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Brillo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(BrilloNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(BrilloButtom)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Contraste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(ContrasteNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ContrastButtom)))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(RotacionCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Rotacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(RotacionNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(RotacionButtom)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(UniqueColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BitsPixel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Width, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Height, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Histogram))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Close)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(convy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(convx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(7, 7, 7)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(DPI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pivoty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pivotx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton3)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );

        convy.getAccessibleContext().setAccessibleName("convy");
        convx.getAccessibleContext().setAccessibleName("convx");
        pivoty.getAccessibleContext().setAccessibleName("pivotey");
        pivotx.getAccessibleContext().setAccessibleName("pivotex");
        jButton3.getAccessibleContext().setAccessibleName("applyConv");

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    private void GrayScaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GrayScaleActionPerformed
        jLabel1.setIcon(new ImageIcon(ObjProcesamiento.escalaGrises(true)));
        ColorUnique();
    }//GEN-LAST:event_GrayScaleActionPerformed

   private void EnabledInit(){
        SaveAs.setEnabled(true);
        Filter.setEnabled(true);
        Rotate.setEnabled(true);
        Umbral.setEnabled(true);
        UmbralNumber.setEnabled(true);
        UmbralButtom.setEnabled(true);
        Brillo.setEnabled(true);
        BrilloNumber.setEnabled(true);
        BrilloButtom.setEnabled(true);
        Contraste.setEnabled(true);
        ContrasteNumber.setEnabled(true);
        ContrastButtom.setEnabled(true);
        RotacionCheck.setEnabled(true);
        Histogram.setEnabled(true);
   }
    
   private void WidthHeight(){
       Width.setText(ObjProcesamiento.getWidth().toString());
       Height.setText(ObjProcesamiento.getHeight().toString());
       DPI.setText(ObjProcesamiento.getDPI());
   }
   
   private void ColorUnique(){
       UniqueColor.setText(ObjProcesamiento.ContarColores().toString());
       BitsPixel.setText(ObjProcesamiento.getBitPixel().toString());
   }
   
    private void UploadImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UploadImageActionPerformed
        jLabel1.setIcon(new ImageIcon(ObjProcesamiento.abrirImagen()));
        if(ObjProcesamiento.imagenCargada()){
            EnabledInit();
            WidthHeight();
            ColorUnique();
        }
    }//GEN-LAST:event_UploadImageActionPerformed

    private void CloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseActionPerformed
        System.exit(1);
    }//GEN-LAST:event_CloseActionPerformed

    private void SaveAsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveAsActionPerformed
        jLabel1.setIcon(new ImageIcon(ObjProcesamiento.guardarImagen()));
    }//GEN-LAST:event_SaveAsActionPerformed

    private void RemoveFiltersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveFiltersActionPerformed
        jLabel1.setIcon(new ImageIcon(ObjProcesamiento.RemoverFiltros()));
        WidthHeight();
        ColorUnique();
    }//GEN-LAST:event_RemoveFiltersActionPerformed

    private void BlackAndWhiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BlackAndWhiteActionPerformed
        jLabel1.setIcon(new ImageIcon(ObjProcesamiento.BlancoYNegro(true)));
        ColorUnique();
    }//GEN-LAST:event_BlackAndWhiteActionPerformed

    private void NegativeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NegativeActionPerformed
       jLabel1.setIcon(new ImageIcon(ObjProcesamiento.Negativo()));
        ColorUnique();
    }//GEN-LAST:event_NegativeActionPerformed

    private void RightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RightActionPerformed
        jLabel1.setIcon(new ImageIcon(ObjProcesamiento.RotarDerecha()));
        WidthHeight();
    }//GEN-LAST:event_RightActionPerformed

    private void LeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LeftActionPerformed
        jLabel1.setIcon(new ImageIcon(ObjProcesamiento.RotarIzquierda()));
        WidthHeight();
    }//GEN-LAST:event_LeftActionPerformed

    private void UmbralStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_UmbralStateChanged
        int a = Umbral.getValue();
        UmbralNumber.setValue(a);
        ObjProcesamiento.CambiarUmbral(a);
        jLabel1.setIcon(new ImageIcon(ObjProcesamiento.BlancoYNegro(false)));
    }//GEN-LAST:event_UmbralStateChanged

    private void UmbralNumberStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_UmbralNumberStateChanged
        int a = (Integer) UmbralNumber.getValue();
        Umbral.setValue(a);
        ObjProcesamiento.CambiarUmbral(a);
        jLabel1.setIcon(new ImageIcon(ObjProcesamiento.BlancoYNegro(false)));
    }//GEN-LAST:event_UmbralNumberStateChanged

    private void ZoomInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZoomInActionPerformed
        jLabel1.setIcon(new ImageIcon(ObjProcesamiento.ZoomIn()));
        WidthHeight();
    }//GEN-LAST:event_ZoomInActionPerformed

    private void SobelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SobelActionPerformed
        jLabel1.setIcon(new ImageIcon(ObjProcesamiento.aplicarConvolucion("conv\\sobelhorinzontal.txt")));
        ColorUnique();
    }//GEN-LAST:event_SobelActionPerformed

    private void ZoomOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZoomOutActionPerformed
       jLabel1.setIcon(new ImageIcon(ObjProcesamiento.ZoomOut()));
       WidthHeight();
    }//GEN-LAST:event_ZoomOutActionPerformed

    private void ContrasteNumberStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_ContrasteNumberStateChanged
        int a = (Integer) ContrasteNumber.getValue();
        Contraste.setValue(a);
        ObjProcesamiento.CambiarContraste(a);
        jLabel1.setIcon(new ImageIcon(ObjProcesamiento.ContrastePN(false)));
    }//GEN-LAST:event_ContrasteNumberStateChanged

    private void RobertsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RobertsActionPerformed
        // TODO add your handling code here:
        jLabel1.setIcon(new ImageIcon(ObjProcesamiento.aplicarConvolucion("conv\\robertspositivo.txt")));
        ColorUnique();
    }//GEN-LAST:event_RobertsActionPerformed

    private void PrewittActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrewittActionPerformed
        // TODO add your handling code here:
        jLabel1.setIcon(new ImageIcon(ObjProcesamiento.aplicarConvolucion("conv\\prewitthorizontal.txt")));
        ColorUnique();
    }//GEN-LAST:event_PrewittActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
        jLabel1.setIcon(new ImageIcon(ObjProcesamiento.aplicarConvolucion("conv\\sobelhorinzontal.txt")));
        ColorUnique();
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void promedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_promedioActionPerformed
        // TODO add your handling code here:
        jLabel1.setIcon(new ImageIcon(ObjProcesamiento.aplicarConvolucion("conv\\promedio7.txt")));
        ColorUnique();
    }//GEN-LAST:event_promedioActionPerformed

    private void laplaceGaussActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laplaceGaussActionPerformed
        // TODO add your handling code here:
        jLabel1.setIcon(new ImageIcon(ObjProcesamiento.aplicarConvolucion("conv\\laplacegauss.txt")));
        ColorUnique();
    }//GEN-LAST:event_laplaceGaussActionPerformed

    private void medianaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medianaActionPerformed
        // TODO add your handling code here:
        jLabel1.setIcon(new ImageIcon(ObjProcesamiento.aplicarMediana(3, 3, 1, 1)));
        ColorUnique();
    }//GEN-LAST:event_medianaActionPerformed

    private void ContrasteStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_ContrasteStateChanged
        int a = (Integer) Contraste.getValue();
        ContrasteNumber.setValue(a);
        ObjProcesamiento.CambiarContraste(a);
        jLabel1.setIcon(new ImageIcon(ObjProcesamiento.ContrastePN(false)));
    }//GEN-LAST:event_ContrasteStateChanged

    private void BrilloStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_BrilloStateChanged
        int a = (Integer) Brillo.getValue();
        BrilloNumber.setValue(a);
        ObjProcesamiento.CambiarBrillo(a);
        jLabel1.setIcon(new ImageIcon(ObjProcesamiento.BrilloPN(false)));
    }//GEN-LAST:event_BrilloStateChanged

    private void BrilloNumberStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_BrilloNumberStateChanged
        int a = (Integer) BrilloNumber.getValue();
        Brillo.setValue(a);
        ObjProcesamiento.CambiarBrillo(a);
        jLabel1.setIcon(new ImageIcon(ObjProcesamiento.BrilloPN(false)));
    }//GEN-LAST:event_BrilloNumberStateChanged

    private void RotacionStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_RotacionStateChanged
        int a = (int) Rotacion.getValue();
        RotacionNumber.setValue(a);
        jLabel1.setIcon(new ImageIcon(ObjProcesamiento.rotacionImagen((double) a,false)));
        WidthHeight();
    }//GEN-LAST:event_RotacionStateChanged

    private void RotacionNumberStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_RotacionNumberStateChanged
        int a = (int) RotacionNumber.getValue();
        Rotacion.setValue(a);
        jLabel1.setIcon(new ImageIcon(ObjProcesamiento.rotacionImagen((double) a,false)));
    }//GEN-LAST:event_RotacionNumberStateChanged

    private void UmbralButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UmbralButtomActionPerformed
        jLabel1.setIcon(new ImageIcon(ObjProcesamiento.BlancoYNegro(true)));
        ColorUnique();
    }//GEN-LAST:event_UmbralButtomActionPerformed

    private void RotacionCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RotacionCheckActionPerformed
        rot=!rot;
        Rotacion.setEnabled(rot);
        RotacionNumber.setEnabled(rot);
        RotacionButtom.setEnabled(rot);
    }//GEN-LAST:event_RotacionCheckActionPerformed

    private void RotacionButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RotacionButtomActionPerformed
        double a = (double) Rotacion.getValue();
        jLabel1.setIcon(new ImageIcon(ObjProcesamiento.rotacionImagen(a,true)));
        WidthHeight();
    }//GEN-LAST:event_RotacionButtomActionPerformed

    private void ContrastButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContrastButtomActionPerformed
        jLabel1.setIcon(new ImageIcon(ObjProcesamiento.ContrastePN(true)));
        ColorUnique();
    }//GEN-LAST:event_ContrastButtomActionPerformed

    private void BrilloButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BrilloButtomActionPerformed
        jLabel1.setIcon(new ImageIcon(ObjProcesamiento.BrilloPN(true)));
        ColorUnique();
    }//GEN-LAST:event_BrilloButtomActionPerformed

    private void HistogramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HistogramActionPerformed
        his.setVisible(true);
    }//GEN-LAST:event_HistogramActionPerformed

    private void convyStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_convyStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_convyStateChanged

    private void convxStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_convxStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_convxStateChanged

    private void pivotyStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_pivotyStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_pivotyStateChanged

    private void pivotxStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_pivotxStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_pivotxStateChanged

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ImageEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ImageEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ImageEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ImageEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ImageEditor().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BitsPixel;
    private javax.swing.JMenuItem BlackAndWhite;
    private javax.swing.JSlider Brillo;
    private javax.swing.JButton BrilloButtom;
    private javax.swing.JSpinner BrilloNumber;
    private javax.swing.JButton Close;
    private javax.swing.JButton ContrastButtom;
    private javax.swing.JSlider Contraste;
    private javax.swing.JSpinner ContrasteNumber;
    private javax.swing.JTextField DPI;
    private javax.swing.JMenu Filter;
    private javax.swing.JMenuItem GrayScale;
    private javax.swing.JTextField Height;
    private javax.swing.JButton Histogram;
    private javax.swing.JMenuItem Left;
    private javax.swing.JMenuItem Negative;
    private javax.swing.JMenuItem Prewitt;
    private javax.swing.JMenuItem RemoveFilters;
    private javax.swing.JMenuItem Right;
    private javax.swing.JMenuItem Roberts;
    private javax.swing.JSlider Rotacion;
    private javax.swing.JButton RotacionButtom;
    private javax.swing.JCheckBox RotacionCheck;
    private javax.swing.JSpinner RotacionNumber;
    private javax.swing.JMenu Rotate;
    private javax.swing.JMenuItem SaveAs;
    private javax.swing.JMenuItem Sobel;
    private javax.swing.JSlider Umbral;
    private javax.swing.JButton UmbralButtom;
    private javax.swing.JSpinner UmbralNumber;
    private javax.swing.JTextField UniqueColor;
    private javax.swing.JMenuItem UploadImage;
    private javax.swing.JTextField Width;
    private javax.swing.JMenuItem ZoomIn;
    private javax.swing.JMenuItem ZoomOut;
    private javax.swing.JSpinner convx;
    private javax.swing.JSpinner convy;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JMenuItem filtroCustom;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem laplaceGauss;
    private javax.swing.JMenuItem mediana;
    private javax.swing.JSpinner pivotx;
    private javax.swing.JSpinner pivoty;
    private javax.swing.JMenuItem promedio;
    // End of variables declaration//GEN-END:variables
}
