/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package imageeditor;

import javax.swing.ImageIcon;

/**
 *
 * @author Leonardo
 */
public class ImageEditor extends javax.swing.JFrame {
    ProcesamientoImagen ObjProcesamiento=new ProcesamientoImagen();
    private boolean rot=false;
    
    public ImageEditor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem4 = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLabel1 = new javax.swing.JLabel();
        Close = new javax.swing.JButton();
        Umbral = new javax.swing.JSlider();
        jLabel2 = new javax.swing.JLabel();
        UniqueColor = new javax.swing.JTextField();
        UmbralNumber = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        Contraste = new javax.swing.JSlider();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ContrasteNumber = new javax.swing.JSpinner();
        Brillo = new javax.swing.JSlider();
        BrilloNumber = new javax.swing.JSpinner();
        Rotacion = new javax.swing.JSlider();
        RotacionNumber = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        RotacionCheck = new javax.swing.JCheckBox();
        UmbralButtom = new javax.swing.JButton();
        BrilloButtom = new javax.swing.JButton();
        ContrastButtom = new javax.swing.JButton();
        RotacionButtom = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        UniqueColor1 = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        UploadImage = new javax.swing.JMenuItem();
        SaveAs = new javax.swing.JMenuItem();
        RemoveFilters = new javax.swing.JMenuItem();
        Filter = new javax.swing.JMenu();
        GrayScale = new javax.swing.JMenuItem();
        BlackAndWhite = new javax.swing.JMenuItem();
        Negative = new javax.swing.JMenuItem();
        Rotate = new javax.swing.JMenu();
        Right = new javax.swing.JMenuItem();
        Left = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        ZoomIn = new javax.swing.JMenuItem();
        ZoomOut = new javax.swing.JMenuItem();
        Umbralización = new javax.swing.JMenuItem();
        Sobel = new javax.swing.JMenuItem();
        BrilloMenu = new javax.swing.JMenuItem();
        contrasteMenu = new javax.swing.JMenuItem();
        Roberts = new javax.swing.JMenuItem();
        Prewitt = new javax.swing.JMenuItem();
        laplaceGauss = new javax.swing.JMenuItem();
        promedio = new javax.swing.JMenuItem();
        mediana = new javax.swing.JMenuItem();
        filtroCustom = new javax.swing.JMenuItem();

        jMenuItem4.setText("jMenuItem4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(jLabel1);

        Close.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Close.setText("Cerrar");
        Close.setFocusable(false);
        Close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseActionPerformed(evt);
            }
        });

        Umbral.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        Umbral.setMajorTickSpacing(255);
        Umbral.setMaximum(255);
        Umbral.setPaintLabels(true);
        Umbral.setPaintTicks(true);
        Umbral.setValue(150);
        Umbral.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Umbral.setEnabled(false);
        Umbral.setFocusable(false);
        Umbral.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                UmbralStateChanged(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel2.setText("Colores Unicos");

        UniqueColor.setEditable(false);
        UniqueColor.setBackground(new java.awt.Color(255, 255, 255));
        UniqueColor.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        UniqueColor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        UniqueColor.setFocusable(false);

        UmbralNumber.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        UmbralNumber.setModel(new javax.swing.SpinnerNumberModel(150, 0, 255, 1));
        UmbralNumber.setToolTipText("");
        UmbralNumber.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        UmbralNumber.setEnabled(false);
        UmbralNumber.setFocusable(false);
        UmbralNumber.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                UmbralNumberStateChanged(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel3.setText("Umbral");

        jButton1.setText("jButton1");

        jButton2.setText("jButton2");

        Contraste.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        Contraste.setMajorTickSpacing(255);
        Contraste.setMaximum(255);
        Contraste.setMinimum(-255);
        Contraste.setMinorTickSpacing(-255);
        Contraste.setPaintLabels(true);
        Contraste.setPaintTicks(true);
        Contraste.setValue(0);
        Contraste.setEnabled(false);
        Contraste.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                ContrasteStateChanged(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel4.setText("Brillo");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel5.setText("Contraste");

        ContrasteNumber.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        ContrasteNumber.setModel(new javax.swing.SpinnerNumberModel(0, -255, 255, 1));
        ContrasteNumber.setToolTipText("");
        ContrasteNumber.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ContrasteNumber.setEnabled(false);
        ContrasteNumber.setFocusable(false);
        ContrasteNumber.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                ContrasteNumberStateChanged(evt);
            }
        });

        Brillo.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        Brillo.setMajorTickSpacing(255);
        Brillo.setMaximum(255);
        Brillo.setMinimum(-255);
        Brillo.setMinorTickSpacing(-255);
        Brillo.setPaintLabels(true);
        Brillo.setPaintTicks(true);
        Brillo.setValue(0);
        Brillo.setEnabled(false);
        Brillo.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                BrilloStateChanged(evt);
            }
        });

        BrilloNumber.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        BrilloNumber.setModel(new javax.swing.SpinnerNumberModel(0, -255, 255, 1));
        BrilloNumber.setToolTipText("");
        BrilloNumber.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BrilloNumber.setEnabled(false);
        BrilloNumber.setFocusable(false);
        BrilloNumber.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                BrilloNumberStateChanged(evt);
            }
        });

        Rotacion.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        Rotacion.setMajorTickSpacing(360);
        Rotacion.setMaximum(360);
        Rotacion.setPaintLabels(true);
        Rotacion.setPaintTicks(true);
        Rotacion.setValue(0);
        Rotacion.setEnabled(false);
        Rotacion.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                RotacionStateChanged(evt);
            }
        });

        RotacionNumber.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        RotacionNumber.setModel(new javax.swing.SpinnerNumberModel(0, 0, 360, 1));
        RotacionNumber.setToolTipText("");
        RotacionNumber.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        RotacionNumber.setEnabled(false);
        RotacionNumber.setFocusable(false);
        RotacionNumber.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                RotacionNumberStateChanged(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel6.setText("Rotacion Libre");

        RotacionCheck.setEnabled(false);
        RotacionCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RotacionCheckActionPerformed(evt);
            }
        });

        UmbralButtom.setText("Aplicar");
        UmbralButtom.setEnabled(false);
        UmbralButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UmbralButtomActionPerformed(evt);
            }
        });

        BrilloButtom.setText("Aplicar");
        BrilloButtom.setEnabled(false);
        BrilloButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BrilloButtomActionPerformed(evt);
            }
        });

        ContrastButtom.setText("Aplicar");
        ContrastButtom.setEnabled(false);
        ContrastButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContrastButtomActionPerformed(evt);
            }
        });

        RotacionButtom.setText("Aplicar");
        RotacionButtom.setEnabled(false);
        RotacionButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RotacionButtomActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel7.setText("DPI");

        UniqueColor1.setEditable(false);
        UniqueColor1.setBackground(new java.awt.Color(255, 255, 255));
        UniqueColor1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        UniqueColor1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        UniqueColor1.setFocusable(false);

        jMenu1.setText("Archivo");
        jMenu1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        UploadImage.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        UploadImage.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        UploadImage.setText("Cargar Imagen");
        UploadImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UploadImageActionPerformed(evt);
            }
        });
        jMenu1.add(UploadImage);

        SaveAs.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_MASK));
        SaveAs.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        SaveAs.setText("Guardar Imagen como...");
        SaveAs.setEnabled(false);
        SaveAs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveAsActionPerformed(evt);
            }
        });
        jMenu1.add(SaveAs);

        RemoveFilters.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        RemoveFilters.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        RemoveFilters.setText("Deshacer Filtros");
        RemoveFilters.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveFiltersActionPerformed(evt);
            }
        });
        jMenu1.add(RemoveFilters);

        Filter.setText("Filtros");
        Filter.setEnabled(false);
        Filter.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        GrayScale.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        GrayScale.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        GrayScale.setText("Escala de Grises");
        GrayScale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GrayScaleActionPerformed(evt);
            }
        });
        Filter.add(GrayScale);
        GrayScale.getAccessibleContext().setAccessibleDescription("");

        BlackAndWhite.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        BlackAndWhite.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        BlackAndWhite.setText("Blanco y Negro");
        BlackAndWhite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BlackAndWhiteActionPerformed(evt);
            }
        });
        Filter.add(BlackAndWhite);

        Negative.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        Negative.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Negative.setText("Negativo");
        Negative.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NegativeActionPerformed(evt);
            }
        });
        Filter.add(Negative);

        jMenu1.add(Filter);

        Rotate.setText("Rotar 90 grados");
        Rotate.setEnabled(false);
        Rotate.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        Right.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        Right.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Right.setText("Derecha");
        Right.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RightActionPerformed(evt);
            }
        });
        Rotate.add(Right);

        Left.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        Left.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Left.setText("Izquierda");
        Left.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LeftActionPerformed(evt);
            }
        });
        Rotate.add(Left);

        jMenu1.add(Rotate);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Tarea2");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        ZoomIn.setText("Zoom In x2");
        ZoomIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZoomInActionPerformed(evt);
            }
        });
        jMenu2.add(ZoomIn);

        ZoomOut.setText("Zoom Out x2");
        ZoomOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZoomOutActionPerformed(evt);
            }
        });
        jMenu2.add(ZoomOut);

        Umbralización.setText("Umbralización");
        Umbralización.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UmbralizaciónActionPerformed(evt);
            }
        });
        jMenu2.add(Umbralización);

        Sobel.setText("Sobel");
        Sobel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SobelActionPerformed(evt);
            }
        });
        jMenu2.add(Sobel);

        BrilloMenu.setText("Brillo");
        BrilloMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BrilloMenuActionPerformed(evt);
            }
        });
        jMenu2.add(BrilloMenu);

        contrasteMenu.setText("Contraste");
        contrasteMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contrasteMenuActionPerformed(evt);
            }
        });
        jMenu2.add(contrasteMenu);

        Roberts.setText("Roberts");
        Roberts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RobertsActionPerformed(evt);
            }
        });
        jMenu2.add(Roberts);

        Prewitt.setText("Prewitt");
        Prewitt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrewittActionPerformed(evt);
            }
        });
        jMenu2.add(Prewitt);

        laplaceGauss.setText("Laplaciano del Gaussiano");
        laplaceGauss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laplaceGaussActionPerformed(evt);
            }
        });
        jMenu2.add(laplaceGauss);

        promedio.setText("Filtro promedio");
        promedio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                promedioActionPerformed(evt);
            }
        });
        jMenu2.add(promedio);

        mediana.setText("Filtro mediana");
        mediana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medianaActionPerformed(evt);
            }
        });
        jMenu2.add(mediana);

        filtroCustom.setText("Filtro Custom");
        jMenu2.add(filtroCustom);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Close)
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(79, 79, 79)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Rotacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(RotacionNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(RotacionButtom))
                                    .addComponent(jLabel3)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Umbral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(UmbralNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(UmbralButtom))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Contraste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(ContrasteNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(ContrastButtom))
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Brillo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(BrilloNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(BrilloButtom))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18)
                                        .addComponent(RotacionCheck))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(18, 18, 18)
                                        .addComponent(UniqueColor1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(UniqueColor, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(80, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UniqueColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 82, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(UniqueColor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Umbral, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(UmbralNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(UmbralButtom)))
                .addGap(25, 25, 25)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Brillo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BrilloNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BrilloButtom)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Contraste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ContrasteNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ContrastButtom)))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(RotacionCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Rotacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(RotacionNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(RotacionButtom)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 138, Short.MAX_VALUE)
                .addComponent(Close)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    private void GrayScaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GrayScaleActionPerformed
        jLabel1.setIcon(new ImageIcon(ObjProcesamiento.escalaGrises(true)));
        UniqueColor.setText(ObjProcesamiento.ContarColores().toString());
    }//GEN-LAST:event_GrayScaleActionPerformed

    private void UploadImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UploadImageActionPerformed
        jLabel1.setIcon(new ImageIcon(ObjProcesamiento.abrirImagen()));
        if(ObjProcesamiento.imagenCargada()){
            SaveAs.setEnabled(true);
            Filter.setEnabled(true);
            Rotate.setEnabled(true);
            Umbral.setEnabled(true);
            UmbralNumber.setEnabled(true);
            UmbralButtom.setEnabled(true);
            Brillo.setEnabled(true);
            BrilloNumber.setEnabled(true);
            BrilloButtom.setEnabled(true);
            Contraste.setEnabled(true);
            ContrasteNumber.setEnabled(true);
            ContrastButtom.setEnabled(true);
            RotacionCheck.setEnabled(true);
            UniqueColor.setText(ObjProcesamiento.ContarColores().toString());
        }
    }//GEN-LAST:event_UploadImageActionPerformed

    private void CloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseActionPerformed
        System.exit(1);
    }//GEN-LAST:event_CloseActionPerformed

    private void SaveAsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveAsActionPerformed
        jLabel1.setIcon(new ImageIcon(ObjProcesamiento.guardarImagen()));
    }//GEN-LAST:event_SaveAsActionPerformed

    private void RemoveFiltersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveFiltersActionPerformed
        jLabel1.setIcon(new ImageIcon(ObjProcesamiento.RemoverFiltros()));
        UniqueColor.setText(ObjProcesamiento.ContarColores().toString());
    }//GEN-LAST:event_RemoveFiltersActionPerformed

    private void BlackAndWhiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BlackAndWhiteActionPerformed
        jLabel1.setIcon(new ImageIcon(ObjProcesamiento.BlancoYNegro(true)));
        UniqueColor.setText(ObjProcesamiento.ContarColores().toString());
    }//GEN-LAST:event_BlackAndWhiteActionPerformed

    private void NegativeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NegativeActionPerformed
       jLabel1.setIcon(new ImageIcon(ObjProcesamiento.Negativo()));
       UniqueColor.setText(ObjProcesamiento.ContarColores().toString());
    }//GEN-LAST:event_NegativeActionPerformed

    private void RightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RightActionPerformed
        jLabel1.setIcon(new ImageIcon(ObjProcesamiento.RotarDerecha()));
    }//GEN-LAST:event_RightActionPerformed

    private void LeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LeftActionPerformed
        jLabel1.setIcon(new ImageIcon(ObjProcesamiento.RotarIzquierda()));
    }//GEN-LAST:event_LeftActionPerformed

    private void UmbralStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_UmbralStateChanged
        int a = Umbral.getValue();
        UmbralNumber.setValue(a);
        ObjProcesamiento.CambiarUmbral(a);
        jLabel1.setIcon(new ImageIcon(ObjProcesamiento.BlancoYNegro(false)));
    }//GEN-LAST:event_UmbralStateChanged

    private void UmbralNumberStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_UmbralNumberStateChanged
        int a = (Integer) UmbralNumber.getValue();
        Umbral.setValue(a);
        ObjProcesamiento.CambiarUmbral(a);
        jLabel1.setIcon(new ImageIcon(ObjProcesamiento.BlancoYNegro(false)));
    }//GEN-LAST:event_UmbralNumberStateChanged

    private void ZoomInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZoomInActionPerformed
        jLabel1.setIcon(new ImageIcon(ObjProcesamiento.ZoomIn()));
    }//GEN-LAST:event_ZoomInActionPerformed

    private void SobelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SobelActionPerformed
         jLabel1.setIcon(new ImageIcon(ObjProcesamiento.aplicarConvolucion("conv\\sobelhorinzontal.txt")));
    }//GEN-LAST:event_SobelActionPerformed

    private void ZoomOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZoomOutActionPerformed
       jLabel1.setIcon(new ImageIcon(ObjProcesamiento.ZoomOut()));
    }//GEN-LAST:event_ZoomOutActionPerformed

    private void ContrasteNumberStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_ContrasteNumberStateChanged
        int a = (Integer) ContrasteNumber.getValue();
        Contraste.setValue(a);
        ObjProcesamiento.CambiarContraste(a);
        jLabel1.setIcon(new ImageIcon(ObjProcesamiento.ContrastePN(false)));
    }//GEN-LAST:event_ContrasteNumberStateChanged

    private void BrilloMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BrilloMenuActionPerformed
        // Brillooooo
        jLabel1.setIcon(new ImageIcon(ObjProcesamiento.aplicarConvolucion("conv\\sobelhorinzontal.txt")));
    }//GEN-LAST:event_BrilloMenuActionPerformed

    private void RobertsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RobertsActionPerformed
        // TODO add your handling code here:
        jLabel1.setIcon(new ImageIcon(ObjProcesamiento.aplicarConvolucion("conv\\robertspositivo.txt")));
    }//GEN-LAST:event_RobertsActionPerformed

    private void PrewittActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrewittActionPerformed
        // TODO add your handling code here:
        jLabel1.setIcon(new ImageIcon(ObjProcesamiento.aplicarConvolucion("conv\\prewitthorizontal.txt")));
    }//GEN-LAST:event_PrewittActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
        jLabel1.setIcon(new ImageIcon(ObjProcesamiento.aplicarConvolucion("conv\\sobelhorinzontal.txt")));
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void promedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_promedioActionPerformed
        // TODO add your handling code here:
        jLabel1.setIcon(new ImageIcon(ObjProcesamiento.aplicarConvolucion("conv\\promedio7.txt")));
    }//GEN-LAST:event_promedioActionPerformed

    private void laplaceGaussActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laplaceGaussActionPerformed
        // TODO add your handling code here:
        jLabel1.setIcon(new ImageIcon(ObjProcesamiento.aplicarConvolucion("conv\\laplacegauss.txt")));
    }//GEN-LAST:event_laplaceGaussActionPerformed

    private void medianaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medianaActionPerformed
        // TODO add your handling code here:
        jLabel1.setIcon(new ImageIcon(ObjProcesamiento.aplicarConvolucion("conv\\mediana.txt")));
    }//GEN-LAST:event_medianaActionPerformed

    private void contrasteMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contrasteMenuActionPerformed
        jLabel1.setIcon(new ImageIcon(ObjProcesamiento.ContrastePN(true)));
    }//GEN-LAST:event_contrasteMenuActionPerformed

    private void UmbralizaciónActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UmbralizaciónActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UmbralizaciónActionPerformed

    private void ContrasteStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_ContrasteStateChanged
        int a = (Integer) Contraste.getValue();
        ContrasteNumber.setValue(a);
        ObjProcesamiento.CambiarContraste(a);
        jLabel1.setIcon(new ImageIcon(ObjProcesamiento.ContrastePN(false)));
    }//GEN-LAST:event_ContrasteStateChanged

    private void BrilloStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_BrilloStateChanged
        int a = (Integer) Brillo.getValue();
        BrilloNumber.setValue(a);
        ObjProcesamiento.CambiarBrillo(a);
        jLabel1.setIcon(new ImageIcon(ObjProcesamiento.BrilloPN(false)));
    }//GEN-LAST:event_BrilloStateChanged

    private void BrilloNumberStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_BrilloNumberStateChanged
        int a = (Integer) BrilloNumber.getValue();
        Brillo.setValue(a);
        ObjProcesamiento.CambiarBrillo(a);
        jLabel1.setIcon(new ImageIcon(ObjProcesamiento.BrilloPN(false)));
    }//GEN-LAST:event_BrilloNumberStateChanged

    private void RotacionStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_RotacionStateChanged
        int a = (int) Rotacion.getValue();
        RotacionNumber.setValue(a);
        jLabel1.setIcon(new ImageIcon(ObjProcesamiento.rotacionImagen((double) a,false)));
    }//GEN-LAST:event_RotacionStateChanged

    private void RotacionNumberStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_RotacionNumberStateChanged
        int a = (int) RotacionNumber.getValue();
        Rotacion.setValue(a);
        jLabel1.setIcon(new ImageIcon(ObjProcesamiento.rotacionImagen((double) a,false)));
    }//GEN-LAST:event_RotacionNumberStateChanged

    private void UmbralButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UmbralButtomActionPerformed
        jLabel1.setIcon(new ImageIcon(ObjProcesamiento.BlancoYNegro(true)));
        UniqueColor.setText(ObjProcesamiento.ContarColores().toString());
    }//GEN-LAST:event_UmbralButtomActionPerformed

    private void RotacionCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RotacionCheckActionPerformed
        rot=!rot;
        Rotacion.setEnabled(rot);
        RotacionNumber.setEnabled(rot);
        RotacionButtom.setEnabled(rot);
    }//GEN-LAST:event_RotacionCheckActionPerformed

    private void RotacionButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RotacionButtomActionPerformed
        double a = (double) Rotacion.getValue();
        jLabel1.setIcon(new ImageIcon(ObjProcesamiento.rotacionImagen(a,true)));
    }//GEN-LAST:event_RotacionButtomActionPerformed

    private void ContrastButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContrastButtomActionPerformed
        jLabel1.setIcon(new ImageIcon(ObjProcesamiento.ContrastePN(true)));
    }//GEN-LAST:event_ContrastButtomActionPerformed

    private void BrilloButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BrilloButtomActionPerformed
        jLabel1.setIcon(new ImageIcon(ObjProcesamiento.BrilloPN(true)));
    }//GEN-LAST:event_BrilloButtomActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ImageEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ImageEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ImageEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ImageEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ImageEditor().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem BlackAndWhite;
    private javax.swing.JSlider Brillo;
    private javax.swing.JButton BrilloButtom;
    private javax.swing.JMenuItem BrilloMenu;
    private javax.swing.JSpinner BrilloNumber;
    private javax.swing.JButton Close;
    private javax.swing.JButton ContrastButtom;
    private javax.swing.JSlider Contraste;
    private javax.swing.JSpinner ContrasteNumber;
    private javax.swing.JMenu Filter;
    private javax.swing.JMenuItem GrayScale;
    private javax.swing.JMenuItem Left;
    private javax.swing.JMenuItem Negative;
    private javax.swing.JMenuItem Prewitt;
    private javax.swing.JMenuItem RemoveFilters;
    private javax.swing.JMenuItem Right;
    private javax.swing.JMenuItem Roberts;
    private javax.swing.JSlider Rotacion;
    private javax.swing.JButton RotacionButtom;
    private javax.swing.JCheckBox RotacionCheck;
    private javax.swing.JSpinner RotacionNumber;
    private javax.swing.JMenu Rotate;
    private javax.swing.JMenuItem SaveAs;
    private javax.swing.JMenuItem Sobel;
    private javax.swing.JSlider Umbral;
    private javax.swing.JButton UmbralButtom;
    private javax.swing.JSpinner UmbralNumber;
    private javax.swing.JMenuItem Umbralización;
    private javax.swing.JTextField UniqueColor;
    private javax.swing.JTextField UniqueColor1;
    private javax.swing.JMenuItem UploadImage;
    private javax.swing.JMenuItem ZoomIn;
    private javax.swing.JMenuItem ZoomOut;
    private javax.swing.JMenuItem contrasteMenu;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JMenuItem filtroCustom;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem laplaceGauss;
    private javax.swing.JMenuItem mediana;
    private javax.swing.JMenuItem promedio;
    // End of variables declaration//GEN-END:variables
}
