/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IEv2;

import java.awt.Graphics2D;
import java.io.File;
import java.util.Stack;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileSystemView;
import org.bytedeco.javacpp.opencv_imgcodecs;
import org.bytedeco.javacpp.opencv_imgproc;
import java.awt.image.BufferedImage;
import javax.swing.ImageIcon;
import org.bytedeco.javacpp.opencv_core;
import org.bytedeco.javacpp.opencv_core.Mat;
import org.bytedeco.javacv.Java2DFrameConverter;
import static org.bytedeco.javacv.Java2DFrameUtils.deepCopy;
import org.bytedeco.javacv.OpenCVFrameConverter;
/**
 *
 * @author FliaMejias
 */
public class IEv2UI extends javax.swing.JPanel {
    Stack<Mat> cntrlz = new Stack<>();
    Stack<Mat> cntrly = new Stack<>();
    Mat original;
    Mat copy;
    static final int maxCntrl = 2;
    String dir = "";
    private static OpenCVFrameConverter.ToMat       matConv = new OpenCVFrameConverter.ToMat();
    private static Java2DFrameConverter             biConv  = new Java2DFrameConverter();

    /*
     * Creates new form IEv2UI
     */
    public IEv2UI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TabbedTareas = new javax.swing.JTabbedPane();
        T1 = new javax.swing.JPanel();
        T2 = new javax.swing.JPanel();
        T3 = new javax.swing.JPanel();
        Cuantizacion = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        FiltroMorfologico = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        UmbralAutomatico = new javax.swing.JComboBox<>();
        CustomMorfologico = new java.awt.TextArea();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        T4 = new javax.swing.JPanel();
        TabbedHistogramas = new javax.swing.JTabbedPane();
        HistogramaR = new java.awt.Canvas();
        HistogramaG = new java.awt.Canvas();
        HistogramaB = new java.awt.Canvas();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        CargarImagen = new javax.swing.JButton();
        GuardarImagen = new javax.swing.JButton();
        canvas4 = new java.awt.Canvas();
        ContainerImage = new javax.swing.JScrollPane();
        ImageDisplay = new javax.swing.JLabel();

        setBackground(new java.awt.Color(142, 174, 189));

        TabbedTareas.setBackground(new java.awt.Color(0, 0, 0));

        T1.setBackground(new java.awt.Color(48, 65, 82));
        T1.setAlignmentX(0.0F);
        T1.setAlignmentY(0.0F);

        javax.swing.GroupLayout T1Layout = new javax.swing.GroupLayout(T1);
        T1.setLayout(T1Layout);
        T1Layout.setHorizontalGroup(
            T1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 299, Short.MAX_VALUE)
        );
        T1Layout.setVerticalGroup(
            T1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
        );

        TabbedTareas.addTab("T1", T1);
        T1.getAccessibleContext().setAccessibleName("T1");

        T2.setBackground(new java.awt.Color(48, 65, 82));
        T2.setAlignmentX(0.0F);
        T2.setAlignmentY(0.0F);

        javax.swing.GroupLayout T2Layout = new javax.swing.GroupLayout(T2);
        T2.setLayout(T2Layout);
        T2Layout.setHorizontalGroup(
            T2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 299, Short.MAX_VALUE)
        );
        T2Layout.setVerticalGroup(
            T2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
        );

        TabbedTareas.addTab("T2", T2);

        T3.setBackground(new java.awt.Color(48, 65, 82));
        T3.setAlignmentX(0.0F);
        T3.setAlignmentY(0.0F);

        Cuantizacion.setMaximumRowCount(3);
        Cuantizacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Paleta", "Redux bits", "K-mean" }));
        Cuantizacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CuantizacionActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cuantización");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Umbral automático");

        FiltroMorfologico.setMaximumRowCount(3);
        FiltroMorfologico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Erosión", "Dilatación", "Apertura", "Cierre" }));
        FiltroMorfologico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FiltroMorfologicoActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Filtro Morfologíco");

        UmbralAutomatico.setMaximumRowCount(3);
        UmbralAutomatico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "OTSU", "OTSUCV", "OTRO METODO" }));
        UmbralAutomatico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UmbralAutomaticoActionPerformed(evt);
            }
        });

        CustomMorfologico.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jSeparator4.setBackground(new java.awt.Color(207, 103, 102));

        jSeparator5.setBackground(new java.awt.Color(207, 103, 102));

        jSeparator6.setBackground(new java.awt.Color(207, 103, 102));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Custom");

        javax.swing.GroupLayout T3Layout = new javax.swing.GroupLayout(T3);
        T3.setLayout(T3Layout);
        T3Layout.setHorizontalGroup(
            T3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(T3Layout.createSequentialGroup()
                .addGroup(T3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(T3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(T3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator6)
                            .addComponent(CustomMorfologico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(T3Layout.createSequentialGroup()
                        .addGroup(T3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(T3Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(T3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(T3Layout.createSequentialGroup()
                                        .addGroup(T3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel2))
                                        .addGap(18, 18, 18)
                                        .addGroup(T3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(UmbralAutomatico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, T3Layout.createSequentialGroup()
                                                .addComponent(Cuantizacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(1, 1, 1))))
                                    .addGroup(T3Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(50, 50, 50)
                                        .addComponent(FiltroMorfologico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(T3Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jLabel4)))
                        .addGap(0, 55, Short.MAX_VALUE)))
                .addContainerGap())
        );
        T3Layout.setVerticalGroup(
            T3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(T3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(T3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cuantizacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(T3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(UmbralAutomatico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(T3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(FiltroMorfologico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CustomMorfologico, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        TabbedTareas.addTab("T3", T3);

        T4.setBackground(new java.awt.Color(48, 65, 82));
        T4.setAlignmentX(0.0F);
        T4.setAlignmentY(0.0F);
        T4.setEnabled(false);

        javax.swing.GroupLayout T4Layout = new javax.swing.GroupLayout(T4);
        T4.setLayout(T4Layout);
        T4Layout.setHorizontalGroup(
            T4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 299, Short.MAX_VALUE)
        );
        T4Layout.setVerticalGroup(
            T4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
        );

        TabbedTareas.addTab("T4", T4);
        T4.getAccessibleContext().setAccessibleName("T4");

        TabbedHistogramas.setBackground(new java.awt.Color(3, 20, 36));
        TabbedHistogramas.addTab("R", HistogramaR);
        TabbedHistogramas.addTab("G", HistogramaG);
        TabbedHistogramas.addTab("B", HistogramaB);

        jSeparator1.setBackground(new java.awt.Color(207, 103, 102));

        jSeparator2.setBackground(new java.awt.Color(207, 103, 102));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator3.setBackground(new java.awt.Color(207, 103, 102));

        CargarImagen.setText("Cargar");
        CargarImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargarImagenActionPerformed(evt);
            }
        });

        GuardarImagen.setText("Guardar");
        GuardarImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarImagenActionPerformed(evt);
            }
        });

        ContainerImage.setBackground(new java.awt.Color(255, 255, 255));
        ContainerImage.setToolTipText("");

        ImageDisplay.setBackground(new java.awt.Color(255, 255, 255));
        ImageDisplay.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        ImageDisplay.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ContainerImage.setViewportView(ImageDisplay);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TabbedHistogramas)
                    .addComponent(TabbedTareas)
                    .addComponent(jSeparator1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jSeparator3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 607, Short.MAX_VALUE)
                                .addComponent(CargarImagen)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(GuardarImagen)
                                .addGap(22, 22, 22))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(ContainerImage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(canvas4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TabbedTareas, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TabbedHistogramas)
                .addGap(19, 19, 19))
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(449, 449, 449)
                                .addComponent(canvas4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ContainerImage)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CargarImagen)
                            .addComponent(GuardarImagen))
                        .addGap(5, 5, 5))
                    .addComponent(jSeparator2))
                .addContainerGap())
        );

        TabbedTareas.getAccessibleContext().setAccessibleName("TabbedTareas");
        TabbedHistogramas.getAccessibleContext().setAccessibleName("TabbedHistograma");
    }// </editor-fold>//GEN-END:initComponents

    private void CuantizacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CuantizacionActionPerformed
        // TODO add your handling code here:
        String content = Cuantizacion.getSelectedItem().toString();
     
        switch (content.toUpperCase()) {
            case "PALETA":

                break;
            case "REDUX BITS":

                break;
            case "K-MEANS":

                break;
            case "":
                break;
            default:
                throw new AssertionError();
        }
    }//GEN-LAST:event_CuantizacionActionPerformed

    
   public Mat extractCustomStructurantElement(){
       int px = 2, py = 2, width = 5, heigth = 5;
       int structurantType = opencv_imgproc.MORPH_ELLIPSE;
       Mat out;
       String structurantTxt = this.CustomMorfologico.getText();
       System.out.println(structurantTxt);
       if(structurantTxt.length() == 1){
           switch(structurantTxt.charAt(0)){
               case '0':
                   structurantType = opencv_imgproc.MORPH_CROSS;
                   break;
               case '1':
                   structurantType = opencv_imgproc.MORPH_RECT;
                   break;
               case '2':
                    structurantType = opencv_imgproc.MORPH_ELLIPSE;
                   break;
                   default:
                       System.out.println("Bad input, se pone por default un elemento\n"
                               + "estructurante eliptico 5 x 5 ");
           }
           
           return opencv_imgproc.getStructuringElement(structurantType, new opencv_core.Size(width, heigth), new opencv_core.Point(2,2));
       }
       return out;
   }
    
    
    private void FiltroMorfologicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FiltroMorfologicoActionPerformed
        // TODO add your handling code here:
        
        String content = this.FiltroMorfologico.getSelectedItem().toString();
        
        if(this.CustomMorfologico.getText().equals("")){
            //usar default
            
        }else{
            //usar custom
            Mat structurantElement = extractCustomStructurantElement();
            
        
        }
        
        switch (content.toUpperCase()) {
            case "EROSIÓN":

                break;
            case "DILATACIÓN":
                
                break;
            case "APERTURA":
                
                break;
            case "CIERRE":
                
                break;
            default:
                throw new AssertionError();
        }
    }//GEN-LAST:event_FiltroMorfologicoActionPerformed

    private void UmbralAutomaticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UmbralAutomaticoActionPerformed
        // TODO add your handling code here:
        String content = this.UmbralAutomatico.getSelectedItem().toString();
        
        switch (content.toUpperCase()) {
            case "OTSU":

                break;
            case "OTSUCV":
                
                break;
            case "OTRO METODO":
                
                break;
            default:
                throw new AssertionError();
        }
    }//GEN-LAST:event_UmbralAutomaticoActionPerformed

    private void CargarImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargarImagenActionPerformed
        // TODO add your handling code here:
        JFileChooser fChooser = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());
        
        if (fChooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
            File fSelected = fChooser.getSelectedFile();
            
            //Cargar
            this.original = opencv_imgcodecs.imread((fSelected.getAbsolutePath()));
            this.copy = this.original.clone();
            BufferedImage aux= toBufferedImage(original);
            //Graphics2D g2 = aux.createGraphics();
            
            //ImageCanvas.printAll(g1);
            ImageDisplay.setIcon(new ImageIcon(aux));
            //Mostrar en Canvas
            //ImageCanvas.paint(this.copy);
            
            
        }  
    }//GEN-LAST:event_CargarImagenActionPerformed

    public synchronized static BufferedImage toBufferedImage(Mat src) {
        return deepCopy(biConv.getBufferedImage(matConv.convert(src).clone()));
    }
    
    
    private void GuardarImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarImagenActionPerformed
        // TODO add your handling code here:
        JFileChooser fChooser = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());
        
        if( fChooser.showSaveDialog(null) == JFileChooser.APPROVE_OPTION){
            File fSelected = fChooser.getSelectedFile();
            
            //Guardar imagen
            opencv_imgcodecs.imwrite(fSelected.getAbsolutePath(), this.copy);
            
        }
    }//GEN-LAST:event_GuardarImagenActionPerformed

public static void pushToStack(Stack<Mat> stack, Mat data){
    Mat copy = null;
    data.copyTo(copy);
    stack.push(copy);
    if(stack.size() > maxCntrl){
        stack.removeElementAt(0);
    }
}
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CargarImagen;
    private javax.swing.JScrollPane ContainerImage;
    private javax.swing.JComboBox<String> Cuantizacion;
    private java.awt.TextArea CustomMorfologico;
    private javax.swing.JComboBox<String> FiltroMorfologico;
    private javax.swing.JButton GuardarImagen;
    private java.awt.Canvas HistogramaB;
    private java.awt.Canvas HistogramaG;
    private java.awt.Canvas HistogramaR;
    private javax.swing.JLabel ImageDisplay;
    private javax.swing.JPanel T1;
    private javax.swing.JPanel T2;
    private javax.swing.JPanel T3;
    private javax.swing.JPanel T4;
    private javax.swing.JTabbedPane TabbedHistogramas;
    private javax.swing.JTabbedPane TabbedTareas;
    private javax.swing.JComboBox<String> UmbralAutomatico;
    private java.awt.Canvas canvas4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    // End of variables declaration//GEN-END:variables
}
